
const EVENT_TYPES = {
  COMMENT: {
    NEW: "COMMENT_NEW",
    REP: "COMMENT_REP",
    UPDATE: "COMMENT_UPDATE",
    DELETE: "COMMENT_DELETE",
    LIKE: "COMMENT_LIKE",
  },
  TASK: {
    NEW: "TASK_NEW",
    UPDATE_DRAG: "UPDATE_DRAG_AND_DROP",
    UPDATE: "UPDATE"
  },
  MEMBER: {
    NEW: "MEMBER_ADD",
  },
  NOTIFICATION: {
    NEW_COMMENT: "NOTIFICATION_NEW_COMMENT",
    DELETE_COMMENT: "NOTIFICATION_DELETE_COMMENT",
    NEW_TASK: "NOTIFICATION_NEW_TASK",
    DELETE_TASK: "NOTIFICATION_DELETE_TASK",
    NEW_MEMBER: "NOTIFICATION_MEMBER_ACCEPT_JOIN_PROJECT",
  }
}

module.exports = EVENT_TYPES;